language: node_js
node_js:
  - 12

script:
  - ng build --prod

before_deploy:
  - tar -zcf marchcharts-${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.tar.gz ./dist/cbb-metrics

deploy:
  provider: script
  script: echo "testing"
  on:
    all_branches: true
